/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/inugami_korone_hololive/scene.gltf 
Author: chained_tan (https://sketchfab.com/ch_fren)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/inugami-korone-hololive-8b89fc7bb19c449baceb403a2995fd78
Title: Inugami Korone (hololive)
*/

import React, { useRef, useEffect, useState } from "react";
import { Suspense } from "react";
import { Canvas } from "@react-three/fiber";
import {
  OrbitControls,
  Preload,
  useGLTF,
  useAnimations,
} from "@react-three/drei";
import * as THREE from "three";

import CanvasLoader from "../Loader";

const Korones = ({ isMobile }) => {
  const group = useRef();

  // ✅ Use the correct model path
  const { scene, animations } = useGLTF("./inugami_korone_hololive/scene.gltf");
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    // ✅ Fix inside-out / interior rendering issue
    scene.traverse((child) => {
      if (child.isMesh) {
        child.material.side = THREE.DoubleSide; // renders both faces
        child.material.depthWrite = true;
        child.material.needsUpdate = true;
        child.castShadow = true;
        child.receiveShadow = true;
      }
    });
  }, [scene]);

  useEffect(() => {
    // ✅ Play first available animation if any exist
    if (names.length > 0) {
      actions[names[0]]?.reset().fadeIn(0.5).play();
    }

    return () => {
      // Cleanup animation on unmount
      if (names.length > 0) {
        actions[names[0]]?.fadeOut(0.5);
      }
    };
  }, [actions, names]);

  return (
    // ✅ Attach ref to group so animations work correctly
    <group ref={group}>
      {/* Soft ambient base */}
      <ambientLight intensity={0.6} />

      {/* Main warm key light from front-top */}
      <directionalLight
        position={[2, 5, 3]}
        intensity={1.5}
        castShadow
        shadow-mapSize-width={1024}
        shadow-mapSize-height={1024}
        color="#fff5e0"
      />

      {/* Pink fill light — gives anime character warmth */}
      <pointLight position={[-3, 2, 2]} intensity={1.2} color="#ffb7c5" />

      {/* Cool blue rim light from behind — adds depth */}
      <pointLight position={[3, 1, -3]} intensity={0.8} color="#a8d8ff" />

      {/* Subtle ground bounce light */}
      <hemisphereLight
        skyColor="#ffffff"
        groundColor="#ffccdd"
        intensity={0.4}
      />

      <primitive
        object={scene}
        scale={isMobile ? 0.5 : 2.5}
        position={isMobile ? [0, -3, 0] : [0, -2.5, 0]}
        rotation={[0, 0.2, 0]} // slight angle looks more natural
      />
    </group>
  );
};

const KoroneCanvas = () => {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const mediaQuery = window.matchMedia("(max-width: 500px)"); // ✅ 300px was too narrow
    setIsMobile(mediaQuery.matches);

    const handleMediaQueryChange = (event) => {
      setIsMobile(event.matches);
    };

    mediaQuery.addEventListener("change", handleMediaQueryChange);
    return () => {
      mediaQuery.removeEventListener("change", handleMediaQueryChange);
    };
  }, []);

  return (
    <Canvas
      frameloop="always" // ✅ "demand" stops animations from playing smoothly
      shadows
      camera={{ position: [0, 2, 5], fov: 45 }} // ✅ slightly closer, lower fov = less distortion
      gl={{
        preserveDrawingBuffer: true,
        antialias: true, // ✅ smoother edges
        alpha: true, // ✅ transparent background
      }}
    >
      <Suspense fallback={<CanvasLoader />}>
        <OrbitControls
          enableZoom={false}
          autoRotate
          autoRotateSpeed={1.5} // ✅ 25 was way too fast — slow and elegant
          maxPolarAngle={Math.PI / 2}
          minPolarAngle={Math.PI / 4} // ✅ prevents looking from directly below
          enablePan={false} // ✅ prevent accidental panning
        />
        <Korones isMobile={isMobile} />
      </Suspense>

      <Preload all />
    </Canvas>
  );
};

export default KoroneCanvas;

useGLTF.preload("./inugami_korone_hololive/scene.gltf");
