/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: chained_tan (https://sketchfab.com/ch_fren)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/inugami-korone-hololive-8b89fc7bb19c449baceb403a2995fd78
Title: Inugami Korone (hololive)
*/

import React, { useRef, useEffect, useState } from "react";
import { Suspense } from "react";
import { Canvas, useThree } from "@react-three/fiber";
import {
  OrbitControls,
  Preload,
  useGLTF,
  useAnimations,
} from "@react-three/drei";
import * as THREE from "three";

import CanvasLoader from "../Loader";

// ─── Auto-fits the model to the canvas viewport ──────────────────────────────
const AutoFitCamera = ({ targetRef }) => {
  const { camera } = useThree();

  useEffect(() => {
    if (!targetRef.current) return;

    // Compute bounding box of the loaded model
    const box = new THREE.Box3().setFromObject(targetRef.current);
    const size = box.getSize(new THREE.Vector3());
    const center = box.getCenter(new THREE.Vector3());

    // Move camera back enough to fit the full model height
    const maxDim = Math.max(size.x, size.y, size.z);
    const fov = camera.fov * (Math.PI / 180);
    let cameraZ = Math.abs(maxDim / (2 * Math.tan(fov / 2)));
    cameraZ *= 1.4; // 1.4x padding so it's not too tight

    camera.position.set(center.x, center.y + size.y * 0.1, cameraZ);
    camera.lookAt(center.x, center.y, center.z);
    camera.updateProjectionMatrix();
  }, [camera, targetRef]);

  return null;
};

// ─── Korone Model ─────────────────────────────────────────────────────────────
const Korones = ({ isMobile }) => {
  const group = useRef();

  const { scene, animations } = useGLTF("./inugami_korone_hololive/scene.gltf");
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    // KHR_materials_unlit = toon/flat shading
    // DoubleSide is already in the GLTF but we enforce it here too
    // Do NOT add heavy lighting — it washes out unlit materials
    scene.traverse((child) => {
      if (child.isMesh) {
        child.material.side = THREE.DoubleSide;
        child.material.depthWrite = true;
        child.material.needsUpdate = true;
      }
    });
  }, [scene]);

  useEffect(() => {
    // Play the ArmatureAction animation
    if (names.length > 0) {
      const action = actions[names[0]];
      if (action) {
        action.reset().fadeIn(0.5).play();
        action.setLoop(THREE.LoopRepeat, Infinity);
      }
    }
    return () => {
      if (names.length > 0) {
        actions[names[0]]?.stop();
      }
    };
  }, [actions, names]);

  // Dynamic scale: fills viewport without skewing
  // The GLTF root already has a 1.8475 scale matrix baked in
  // so we keep our scale modest
  const scale = isMobile ? 0.28 : 0.42;

  // Center it vertically — adjust yOffset to taste
  const yOffset = isMobile ? -1.0 : -1.5;

  return (
    // ✅ ref on group so animations bind correctly to skeleton
    <group ref={group}>
      {/* 
        KHR_materials_unlit ignores most lights but ambient still
        provides a base fill so the model isn't pitch black in dark scenes
      */}
      <ambientLight intensity={1.2} />

      {/*
        Soft directional for mild shadow definition only
        Keep intensity LOW — unlit materials look best with minimal lighting
      */}
      <directionalLight position={[2, 4, 3]} intensity={0.3} color="#ffffff" />

      <primitive
        object={scene}
        scale={scale}
        position={[0, yOffset, 0]}
        rotation={[0, 0.15, 0]}
      />
    </group>
  );
};

// ─── Canvas Wrapper ───────────────────────────────────────────────────────────
const KoroneCanvas = () => {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    // 500px is a sensible mobile breakpoint
    const mediaQuery = window.matchMedia("(max-width: 500px)");
    setIsMobile(mediaQuery.matches);

    const handleMediaQueryChange = (event) => setIsMobile(event.matches);
    mediaQuery.addEventListener("change", handleMediaQueryChange);
    return () =>
      mediaQuery.removeEventListener("change", handleMediaQueryChange);
  }, []);

  return (
    <Canvas
      frameloop="always"
      shadows={false} // unlit models don't cast real shadows
      dpr={[1, 2]} // responsive pixel ratio — crisp on retina, not heavy on low-end
      camera={{
        position: [0, 0.5, 5], // 👈 lower camera Y from 1.5 → 0.5, looks up slightly at her
        fov: 38,
        near: 0.1,
        far: 100,
      }}
      style={{
        width: "100%",
        height: "100%",
      }}
      gl={{
        preserveDrawingBuffer: true,
        antialias: true,
        alpha: true, // transparent canvas background
        outputColorSpace: THREE.SRGBColorSpace,
      }}
    >
      <Suspense fallback={<CanvasLoader />}>
        <OrbitControls
          enableZoom={false}
          enablePan={false}
          autoRotate
          autoRotateSpeed={1.2} // slow, elegant rotation
          maxPolarAngle={Math.PI / 1.8} // can look slightly above
          minPolarAngle={Math.PI / 3} // can't look from too far below
          target={[0, 1.2, 0]} // orbit around upper body, not feet
        />
        <Korones isMobile={isMobile} />
      </Suspense>

      <Preload all />
    </Canvas>
  );
};

export default KoroneCanvas;

useGLTF.preload("./inugami_korone_hololive/scene.gltf");
